# Generated by Django 4.2.16 on 2025-07-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='mri_images/')),
                ('label', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('tumor', 'Tumor')], max_length=20)),
            ],
        ),
    ]
